/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import Styles from '../styles/home.module.css'
import Link from 'next/link'
import { useEffect, useRef } from 'react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>bike Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="module"
          src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"
        ></script>
        <script
          nomodule
          src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"
        ></script>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css"
        />
      </Head>
      <div className={Styles.mainSec}>
        <div className={Styles.header}>
          <div className={Styles.logo}>
            <img src="/images/logo.png" alt="" />
          </div>
          <div className={Styles.navbar}>
            <ul>
              <li>
                <Link href={'/'}>
                  <a>Features</a>
                </Link>
              </li>
              <li>
                <Link href={'/'}>
                  <a>Gallary</a>
                </Link>
              </li>
              <li>
                <Link href={'/'}>
                  <a>Store</a>
                </Link>
              </li>
              <li>
                <Link href={'/'}>
                  <a>Contact</a>
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className={Styles.mainContent}>
          <h2>
            Ready to <span>Race</span>
          </h2>

          <Link href={'/'}>
            <a className={Styles.rideBtn}>Ride Now</a>
          </Link>

          <img src="/images/bike.png" alt="" />
        </div>

        <div className={Styles.footer}>
          <ul>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-facebook"></ion-icon>
                </a>
              </Link>
            </li>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-youtube"></ion-icon>
                </a>
              </Link>
            </li>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-instagram"></ion-icon>
                </a>
              </Link>
            </li>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-twitch"></ion-icon>
                </a>
              </Link>
            </li>
          </ul>
          <div className={Styles.dots}>
            <div className={`${Styles.dot} ${Styles.active}`}></div>
            {/* <div className={Styles['dot'] + ' ' + Styles['active']}></div> */}
            <div className={Styles['dot']}></div>
            <div className={Styles['dot']}></div>
          </div>
        </div>
      </div>
    </div>
  )
}
