/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import Styles from '../styles/home.module.css'
import Link from 'next/link'
import { useEffect, useRef } from 'react'

export default function Home() {
  const firstRef = useRef(null)
  const secondRef = useRef(null)
  const thirdRef = useRef(null)
  const navRef = useRef(null)

  const firstSliderRef = useRef(null)
  const secondSliderRef = useRef(null)
  const thirdSliderRef = useRef(null)

  const firstText = () => {
    if (secondRef.current.classList.contains('home_active__GWg4y')) {
      secondRef.current.classList.remove('home_active__GWg4y')
      firstRef.current.classList.add('home_active__GWg4y')
    } else if (thirdRef.current.classList.contains('home_active__GWg4y')) {
      thirdRef.current.classList.remove('home_active__GWg4y')
      firstRef.current.classList.add('home_active__GWg4y')
    }

    if (
      secondSliderRef.current.classList.contains('home_sliderOne__8kGoN') ||
      thirdSliderRef.current.classList.contains('home_sliderOne__8kGoN')
    ) {
      firstSliderRef.current.classList.add('home_sliderOne__8kGoN')
      secondSliderRef.current.classList.remove('home_sliderOne__8kGoN')
      thirdSliderRef.current.classList.remove('home_sliderOne__8kGoN')
    }
  }

  const secondText = () => {
    if (firstRef.current.classList.contains('home_active__GWg4y')) {
      firstRef.current.classList.remove('home_active__GWg4y')
      secondRef.current.classList.add('home_active__GWg4y')
    } else if (thirdRef.current.classList.contains('home_active__GWg4y')) {
      thirdRef.current.classList.remove('home_active__GWg4y')
      secondRef.current.classList.add('home_active__GWg4y')
    }

    if (
      firstSliderRef.current.classList.contains('home_sliderOne__8kGoN') ||
      thirdSliderRef.current.classList.contains('home_sliderOne__8kGoN')
    ) {
      firstSliderRef.current.classList.remove('home_sliderOne__8kGoN')
      thirdSliderRef.current.classList.remove('home_sliderOne__8kGoN')
      secondSliderRef.current.classList.add('home_sliderOne__8kGoN')
    }
  }
  const thirdText = () => {
    if (firstRef.current.classList.contains('home_active__GWg4y')) {
      firstRef.current.classList.remove('home_active__GWg4y')
      thirdRef.current.classList.add('home_active__GWg4y')
    } else if (secondRef.current.classList.contains('home_active__GWg4y')) {
      secondRef.current.classList.remove('home_active__GWg4y')
      thirdRef.current.classList.add('home_active__GWg4y')
    }
    if (
      firstSliderRef.current.classList.contains('home_sliderOne__8kGoN') ||
      secondSliderRef.current.classList.contains('home_sliderOne__8kGoN')
    ) {
      firstSliderRef.current.classList.remove('home_sliderOne__8kGoN')
      secondSliderRef.current.classList.remove('home_sliderOne__8kGoN')
      thirdSliderRef.current.classList.add('home_sliderOne__8kGoN')
    }
  }

  const menuChanger = () => {
    console.log(navRef)
    if (navRef.current.classList.contains('home_navSlide__dAswv')) {
      navRef.current.classList.remove('home_navSlide__dAswv')
    } else {
      navRef.current.classList.add('home_navSlide__dAswv')
    }
    // home_navSlide__dAswv
  }

  return (
    <div>
      <Head>
        <title>Suzuki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/suziki/favicon.ico" />
        <script
          type="module"
          src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"
        ></script>
        <script
          nomodule
          src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"
        ></script>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css"
        />
      </Head>
      <div className={Styles.mainSec}>
        <div className={Styles.header}>
          <div className={Styles.mainMenu}>
            <div className={Styles.logo}>
              <img src="/images/logo.png" alt="" />
            </div>
            <div className={Styles.menu}>
              <a onClick={menuChanger}>
                <ion-icon name="grid-outline"></ion-icon>
              </a>
            </div>
          </div>
          <div ref={navRef} className={`${Styles.navbar} `}>
            <ul>
              <li>
                <Link href={'/'}>
                  <a>Features</a>
                </Link>
              </li>
              <li>
                <Link href={'/'}>
                  <a>Gallary</a>
                </Link>
              </li>
              <li>
                <Link href={'/'}>
                  <a>Store</a>
                </Link>
              </li>
              <li>
                <Link href={'/'}>
                  <a>Contact</a>
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className={Styles.mainContent}>
          <h2>
            Ready to <span>Race</span>
          </h2>

          <Link href={'/'}>
            <a className={Styles.rideBtn}>Ride Now</a>
          </Link>

          <img src="/images/bike.png" alt="" />
        </div>

        <div className={`${Styles.slider}`}>
          <div
            ref={firstSliderRef}
            className={`${Styles.sliders} ${Styles.sliderOne}`}
          >
            <h2>
              <span>Engine</span>
              <br />
              599 CC
            </h2>
            <h2>
              <span>Max Speed</span>
              <br />
              260 Kmph
            </h2>
          </div>
          <div ref={secondSliderRef} className={Styles.sliders}>
            <h2>
              <span>Millage</span>
              <br />
              13 Kmpl
            </h2>
            <h2>
              <span>0 - 100 Kmph</span>
              <br />
              4.5 Second
            </h2>
          </div>
          <div ref={thirdSliderRef} className={Styles.sliders}>
            <h2>
              <span>Wheels</span>
              <br />
              16 inch
            </h2>
            <h2>
              <span>Tyre </span>
              <br />
              Tubeless
            </h2>
          </div>
        </div>

        <div className={Styles.footer}>
          <ul>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-facebook"></ion-icon>
                </a>
              </Link>
            </li>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-youtube"></ion-icon>
                </a>
              </Link>
            </li>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-instagram"></ion-icon>
                </a>
              </Link>
            </li>
            <li>
              <Link href={'/'}>
                <a>
                  <ion-icon name="logo-twitch"></ion-icon>
                </a>
              </Link>
            </li>
          </ul>
          <div className={Styles.dots}>
            <div
              ref={firstRef}
              className={`${Styles.dot} ${Styles.active}`}
              onClick={firstText}
            ></div>
            <div
              ref={secondRef}
              className={`${Styles.dot}`}
              onClick={secondText}
            ></div>
            <div
              ref={thirdRef}
              className={Styles['dot']}
              onClick={thirdText}
            ></div>
          </div>
        </div>
      </div>
    </div>
  )
}
